### ISSUE TITLE
run index.js locally with lambda-local?

### ISSUE THREAD

**Issue by zaxy78** [smithclay/lambdium#21]
I get this error:
```
Error: The specified executable path does not exist: /var/task/bin/chromedriver
    at new DriverService.Builder (/Users/asachs/Documents/projects/GitHub/lambdium/node_modules/selenium-webdriver/remote/index.js:330:13)
    at new ServiceBuilder (/Users/asachs/Documents/projects/GitHub/lambdium/node_modules/selenium-webdriver/chrome.js:222:5)
    at Object.exports.createSession (/Users/asachs/Documents/projects/GitHub/lambdium/lib/chromium.js:52:15)
    at Object.<anonymous> (/Users/asachs/Documents/projects/GitHub/lambdium/index.js:16:23)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
```

**Comment by zaxy78** [comment]
I have the `chromedriver` under bin after running `./scripts/fetch-dependencies.sh`

**Comment by smithclay** [comment]
Hi @zaxy78, you'll need to redeploy the function after running `fetch-dependencies`—if you've confirmed `chromedriver` is under the `bin` directory, you should be good to go.
